import {
  Activity,
  AlarmClock,
  Archive,
  Atom,
  BadgeCheck,
  Banknote,
  Bell,
  Bike,
  BookOpen,
  Bot,
  Box,
  BriefcaseBusiness,
  Bug,
  Building2,
  CalendarDays,
  Camera,
  ChartNoAxesCombined,
  CheckCircle2,
  CircleHelp,
  ClipboardList,
  Cloud,
  Code2,
  Coffee,
  Compass,
  CreditCard,
  Database,
  FileText,
  Flag,
  Flame,
  FolderOpen,
  Gamepad2,
  Gift,
  Globe2,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Image,
  KeyRound,
  Languages,
  Laptop,
  Leaf,
  Lightbulb,
  Link2,
  LockKeyhole,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Mic2,
  MonitorPlay,
  Moon,
  MousePointer2,
  Music2,
  NotebookTabs,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  Plane,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Target,
  TerminalSquare,
  Trophy,
  Users,
  WandSparkles,
  Wifi,
  Workflow,
  Zap,
} from "lucide-react";
import type { IconItem } from "../src";

const entries = [
  ["activity", "Activity", Activity, "General"],
  ["alarm-clock", "Alarm clock", AlarmClock, "Time"],
  ["archive", "Archive", Archive, "Files"],
  ["atom", "Atom", Atom, "Science"],
  ["badge-check", "Verified", BadgeCheck, "Status"],
  ["banknote", "Money", Banknote, "Finance"],
  ["bell", "Notifications", Bell, "Communication"],
  ["bike", "Bike", Bike, "Travel"],
  ["book-open", "Knowledge", BookOpen, "Files"],
  ["bot", "Agent", Bot, "Technology"],
  ["box", "Box", Box, "Commerce"],
  ["briefcase", "Business", BriefcaseBusiness, "Work"],
  ["bug", "Bug", Bug, "Technology"],
  ["building", "Company", Building2, "Work"],
  ["calendar", "Calendar", CalendarDays, "Time"],
  ["camera", "Camera", Camera, "Media"],
  ["chart", "Analytics", ChartNoAxesCombined, "Data"],
  ["check-circle", "Complete", CheckCircle2, "Status"],
  ["help", "Help", CircleHelp, "Communication"],
  ["clipboard", "Tasks", ClipboardList, "Work"],
  ["cloud", "Cloud", Cloud, "Technology"],
  ["code", "Code", Code2, "Technology"],
  ["coffee", "Coffee", Coffee, "Food"],
  ["compass", "Explore", Compass, "Travel"],
  ["credit-card", "Payment", CreditCard, "Finance"],
  ["database", "Database", Database, "Data"],
  ["file-text", "Document", FileText, "Files"],
  ["flag", "Flag", Flag, "Status"],
  ["flame", "Trending", Flame, "Status"],
  ["folder-open", "Folder", FolderOpen, "Files"],
  ["gamepad", "Gaming", Gamepad2, "Entertainment"],
  ["gift", "Gift", Gift, "Commerce"],
  ["globe", "Global", Globe2, "Travel"],
  ["graduation-cap", "Education", GraduationCap, "Education"],
  ["headphones", "Audio", Headphones, "Media"],
  ["heart", "Favorite", Heart, "Status"],
  ["home", "Home", Home, "General"],
  ["image", "Image", Image, "Media"],
  ["key", "Access", KeyRound, "Security"],
  ["languages", "Languages", Languages, "Communication"],
  ["laptop", "Laptop", Laptop, "Technology"],
  ["leaf", "Nature", Leaf, "Nature"],
  ["lightbulb", "Idea", Lightbulb, "General"],
  ["link", "Link", Link2, "General"],
  ["lock", "Private", LockKeyhole, "Security"],
  ["mail", "Email", Mail, "Communication"],
  ["map", "Map", Map, "Travel"],
  ["megaphone", "Announcement", Megaphone, "Communication"],
  ["message", "Chat", MessageCircle, "Communication"],
  ["microphone", "Voice", Mic2, "Media"],
  ["monitor-play", "Video", MonitorPlay, "Media"],
  ["moon", "Night", Moon, "Nature"],
  ["cursor", "Pointer", MousePointer2, "General"],
  ["music", "Music", Music2, "Media"],
  ["notebook", "Notes", NotebookTabs, "Files"],
  ["package", "Package", Package, "Commerce"],
  ["palette", "Design", Palette, "Creative"],
  ["paperclip", "Attachment", Paperclip, "Files"],
  ["party", "Celebration", PartyPopper, "Entertainment"],
  ["plane", "Flight", Plane, "Travel"],
  ["rocket", "Launch", Rocket, "Technology"],
  ["search", "Search", Search, "General"],
  ["settings", "Settings", Settings, "General"],
  ["shield-check", "Secure", ShieldCheck, "Security"],
  ["shopping-bag", "Shopping", ShoppingBag, "Commerce"],
  ["sparkles", "Magic", Sparkles, "Creative"],
  ["star", "Star", Star, "Status"],
  ["sun", "Day", Sun, "Nature"],
  ["target", "Goal", Target, "Work"],
  ["terminal", "Terminal", TerminalSquare, "Technology"],
  ["trophy", "Achievement", Trophy, "Status"],
  ["users", "Team", Users, "Work"],
  ["wand", "Create", WandSparkles, "Creative"],
  ["wifi", "Connected", Wifi, "Technology"],
  ["workflow", "Workflow", Workflow, "Work"],
  ["zap", "Fast", Zap, "Status"],
] as const;

export const demoIcons: IconItem[] = entries.map(
  ([id, label, Component, category]) => ({
    id,
    label,
    category,
    keywords: [category.toLowerCase()],
    icon: <Component aria-hidden="true" />,
  }),
);
